In [3]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [4]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
("that was the best meal i've ever had in my life", "positive"),
("i feel so grateful for everything i have in my life", "positive"),
("i received a promotion at work and i couldn't be happier", "positive"),
("watching a beautiful sunset always fills me with joy", "positive"),
("my partner surprised me with a thoughtful gift and it made my day", "positive"),
("i am so proud of my daughter for graduating with honors", "positive"),
("listening to my favorite music always puts me in a good mood", "positive"),
("i love the feeling of accomplishment after completing a challenging task", "positive"),
("i am excited to go on vacation next week", "positive"),
("i feel so overwhelmed with work and responsibilities", "negative"),
("the traffic during my commute is always so frustrating", "negative"),
("i received a parking ticket and it ruined my day", "negative"),
("i got into an argument with my partner and we're not speaking", "negative"),
("i have a headache and i feel terrible", "negative"),
("i received a rejection letter for the job i really wanted", "negative"),
("my car broke down and it's going to be expensive to fix", "negative"),
("i'm feeling sad because i miss my friends who live far away", "negative"),
("i'm frustrated because i can't seem to make progress on my project", "negative"),
("i'm disappointed because my team lost the game", "negative")],
                   columns = ['text', 'sentiment'])

In [5]:
data.head()

                                                text sentiment
0    i love spending time with my friends and family  positive
1    that was the best meal i've ever had in my life  positive
2  i feel so grateful for everything i have in my...  positive
3  i received a promotion at work and i couldn't ...  positive
4  watching a beautiful sunset always fills me wi...  positive

In [6]:
data = data.sample(frac = 1).reset_index(drop = True)

In [7]:
X = data['text']
y = data['sentiment']

In [8]:
countvec = CountVectorizer()

In [10]:
countvec_fie = countvec.fit_transform(X)

In [12]:
bag_of_words = pd.DataFrame(countvec_fie.toarray(), columns = countvec.get_feature_names_out()) # var should have been countvec_fit, but has a typo

In [13]:
bag_of_words

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
7,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
10,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
17,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
19,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, y, test_size = 0.3, random_state = 7)

## Logistic Regression

In [15]:
lr = LogisticRegression(random_state = 1).fit(X_train, y_train)

In [18]:
y_pred_lr = lr.predict(X_test)

In [19]:
accuracy_score(y_pred_lr, y_test)

0.3333333333333333

In [21]:
print(classification_report(y_test, y_pred_lr, zero_division = 0))

              precision    recall  f1-score   support

    negative       0.33      0.33      0.33         3
    positive       0.33      0.33      0.33         3

    accuracy                           0.33         6
   macro avg       0.33      0.33      0.33         6
weighted avg       0.33      0.33      0.33         6

## Naive Bayes

In [22]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
nb = MultinomialNB().fit(X_train, y_train)

In [25]:
y_pred_nb = nb.predict(X_test)

In [26]:
accuracy_score(y_pred_nb, y_test)

0.3333333333333333

## SVM (Linear Support Vector Machine)

In [27]:
from sklearn.linear_model import SGDClassifier

In [28]:
svm = SGDClassifier().fit(X_train, y_train)

In [30]:
y_pred_svm = svm.predict(X_test)

In [31]:
accuracy_score(y_pred_svm, y_test)

0.5